version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ayushsetu
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  app:
    build: .
    command: ["python", "-m", "src.utils.build_master_db"]
    volumes:
      - .:/app
    environment:
      WHO_TERMINOLOGIES_MASTER_DB: /app/data/master.db
      WHO_TERMINOLOGIES_JSON_FOLDER: /app/data/who_terminologies/json
      PGHOST: db
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: ayushsetu
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      PYTHONPATH: /app
    depends_on:
      - db
      - redis

volumes:
  pgdata:
  redisdata:
